language: java
sudo: false
install: true
addons:
  sonarqube:
    token:
      secure: "26c7356b668aa94331cdbe5cf2762f880524d30b"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'