dist: trusty
sudo: required

addons:
  sonarqube:
    token:
      secure: "26c7356b668aa94331cdbe5cf2762f880524d30b"
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
